services:
  app:
    build: .
    container_name: python-metrics-demo-app
    environment:
      - APP_NAME=python-metrics-demo
      - APP_VERSION=1.0.0
      - APP_ENV=docker
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: python-metrics-demo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app
